Readme of game execution.
SOMAS2020/SOMAS2020 pull request #163
Opened 2020-12-28 15:17 UTC by Eirikalb

# Summary

Adds documentation for the order of execution in the game

## Additional Information

Provides overview and some detail about functions and where to find them in the repo. The entries are ordered consecutively in terms of execution order.

## Test Plan
No testing, its a readme....

2020-12-28 15:17 UTC, QFSW commented
# ⚠️Warning! This diff contains changes in protected folders

2020-12-28 15:35 UTC, lhl2617 commented on ExecutionOrder.md
> +|internal/server/turn.go|startOfTurnUpdate| Sends update of gameState to alive clients. |
changed

2020-12-28 22:14 UTC, Darrekt reviewed
A welcome addition :)

2020-12-29 18:31 UTC, NGovani commented on ExecutionOrder.md
> +|internal/server/iifo.go|distributePreictions|Share predictions with islands of your choice. Islands who receive a prediction(s) do not know who else receieved the same prediciton(s).|
distributePredictions*

2020-12-29 18:56 UTC, NGovani requested changes
Once PR #173 gets merged in, this will need some overhauls. Could we wait for that then update this PR

2020-12-29 18:56 UTC, NGovani commented on ExecutionOrder.md
> +|internal/server/iito.go|runIITOEndOfTurn| To be implemented. |
Now updates the server state as well as notifies clients

2020-12-29 18:56 UTC, NGovani commented on ExecutionOrder.md
> +- internal/server/iigointernal/orchestration.go - what happens if president and judge can be paid but speaker can't be? How are the salaries that are taken from the pool and stored returned back to t
@Neelesh99 Correct me if im wrong, but if any of the three roles cannot be paid then all salaries are given back to the common pool in the returnWithdrawnSalariesToCommonPool function.

2020-12-30 13:30 UTC, lhl2617 commented
@NGovani passing this on to you bc you are most familiar

2021-01-03 16:24 UTC, NGovani commented
pr #251 will replace this

2021-01-03 16:24 UTC, closed without merging