[IITO] Agents can shared intended common pool donations
SOMAS2020/SOMAS2020 pull request #257
Opened 2021-01-04 10:22 UTC by Eirikalb

# Summary

Agents can share intended common pool donations in a new IITO session
## Additional Information

Auxiliary information goes here.

## Test Plan

- Test the distribution of the contribution intentions

2021-01-04 13:04 UTC, lhl2617 commented on internal/common/baseclient/iito.go
> +// ShareIntendedContributionis called on each client to give them the
```suggestion
// ShareIntendedContribution is called on each client to give them the
```

2021-01-04 13:55 UTC, Darrekt approved these changes
Thank you for writing a test with your code <3

2021-01-04 13:55 UTC, Darrekt commented on internal/server/iito.go
> +
No need for this newline (petty nitpick)

2021-01-04 13:55 UTC, Darrekt commented on internal/server/iito.go
> +	for _, id := range nonDeadClients {
```suggestion
	for _, id := range getNonDeadClientIDs(s.gameState.ClientInfos) {
```

2021-01-04 13:55 UTC, Darrekt commented on internal/server/iito.go
> +		islandPredictionsDict[id] = c.ShareIntendedContribution()
```suggestion
		islandPredictionsDict[id] = s.clientMap[id].ShareIntendedContribution()
```

2021-01-04 13:59 UTC, Darrekt commented on internal/common/shared/contribution.go
> +	Contribution float64
Should be `Resource` instead of `float64`

2021-01-04 13:59 UTC, Darrekt commented on internal/common/shared/contribution.go
> +	Contribution float64
Same here, needs to change throughout the PR.

2021-01-04 14:00 UTC, Darrekt requested changes, later dismissed
Sorry, missed it during my first review. Please change all `float64`'s representing contributions to `Resources`

2021-01-04 14:05 UTC, Darrekt commented on internal/server/iito_test.go
> +}
![image](https://user-images.githubusercontent.com/44197672/103543075-d5438e00-4e95-11eb-83af-3e9c3001652b.png)

2021-01-04 14:08 UTC, E-Mac27 reviewed
👍 Nice.

2021-01-04 14:08 UTC, E-Mac27 commented on internal/common/baseclient/iito.go
> +func (c *BaseClient) ShareIntendedContribution() shared.IntendedContribution {
Please add Compulsory/Optional

2021-01-04 16:37 UTC, Eirikalb commented
> Sorry, missed it during my first review. Please change all `float64`'s representing contributions to `Resources`

Done this now

2021-01-04 19:49 UTC, NGovani approved these changes
Some issues with the base client but the infra stuff looks good enough to merge

2021-01-04 19:49 UTC, NGovani commented on internal/common/baseclient/iito.go
> +	for index, id := range shared.TeamIDs {
Would be better to use the nonDeadAgents functionality through the ServerReadHandle

2021-01-04 19:49 UTC, NGovani commented on internal/common/baseclient/iito.go
> +// COMPULSORY, you must implement this function
should be switched to Optional, or the other function should be made compulsory. I'd rather both be compulsary

2021-01-05 11:32 UTC, Eirikalb commented on internal/common/baseclient/iito.go
> +	for index, id := range shared.TeamIDs {
Agreed

2021-01-05 11:32 UTC, Eirikalb commented on internal/common/baseclient/iito.go
> +// COMPULSORY, you must implement this function
Agreed

2021-01-05 11:39 UTC, merged