Add Structure section and team 1 README
SOMAS2020/SOMAS2020 pull request #7
Opened 2020-11-27 13:28 UTC by Darrekt

# Summary

Please provide a summary of the change.

## Additional Information

Auxiliary information goes here.

## Test Plan

- Add information on how you tested your changes.

- `go test ./...`
```
Paste logs here
```

- `go run .`
```
Paste logs here
```

2020-11-27 14:53 UTC, lhl2617 commented on README.md
> +### `Docs`
lowercase d

2020-11-27 14:53 UTC, lhl2617 commented on README.md
> + #### `common`
whitespace?

2020-11-27 14:53 UTC, lhl2617 requested changes
add missing details + small nits in readme

2020-11-27 19:16 UTC, lhl2617 commented on internal/clients/team1/README.md
> +| Infrastructure | Lee Lin Hao (LH) | lhl2617 | lhl2617 |
`Lin Hao Lee` preferred but this is fine 👍

2020-11-28 09:26 UTC, Darrekt reviewed
Fixed all requests

2020-11-28 09:58 UTC, lhl2617 commented on README.md
> + #### `common`
White space between LHS and ####?

2020-11-28 10:00 UTC, lhl2617 approved these changes
Preapproving--pls merge after fixing white space :)

2020-11-30 17:11 UTC, merged